
namespace ServiceAPI.Entities
{
	
	public class ct64
	{
        public string stt_rec { get; set; }
        public string ma_ct { get; set; }
        public System.DateTime ngay_ct { get; set; }
        public string so_ct { get; set; }
        public System.DateTime ngay_de_nghi_gh { get; set; }
        public System.DateTime ngay_hua_gh { get; set; }
        public System.DateTime ngay_ch { get; set; }
        public string thoi_gian_ch { get; set; }
        public System.DateTime ngay_gh { get; set; }
        public string ma_lo { get; set; }
        public string ma_vt { get; set; }
        public string dvt { get; set; }
        public decimal he_so { get; set; }
        public decimal so_luong { get; set; }
        public decimal so_luong_can_chuyen { get; set; }
        public decimal so_luong_can_hoa_don { get; set; }
        public decimal so_luong_can_tra_lai { get; set; }
        public decimal so_luong_da_chuyen { get; set; }
        public decimal so_luong_da_tra_lai { get; set; }
        public decimal so_luong_da_hoa_don { get; set; }
        public decimal sl_dc_chua_hoa_don { get; set; }
        public decimal sl_tl_chua_hoa_don { get; set; }
        public decimal so_luong0 { get; set; }
        public decimal so_luong0_can_chuyen { get; set; }
        public decimal so_luong0_can_hoa_don { get; set; }
        public decimal so_luong0_can_tra_lai { get; set; }
        public decimal so_luong0_da_chuyen { get; set; }
        public decimal so_luong0_da_tra_lai { get; set; }
        public decimal so_luong0_da_hoa_don { get; set; }
        public decimal sl0_dc_chua_hoa_don { get; set; }
        public decimal sl0_tl_chua_hoa_don { get; set; }
        public string ma_kho { get; set; }
        public string ma_vi_tri { get; set; }
        public short px_gia_dd { get; set; }
        public decimal gia_nt2 { get; set; }
        public decimal gia2 { get; set; }
        public decimal tien_nt2 { get; set; }
        public decimal tien2 { get; set; }
        public decimal gia_nt { get; set; }
        public decimal gia { get; set; }
        public decimal tien_nt { get; set; }
        public decimal tien { get; set; }
        public decimal cp_bh_nt { get; set; }
        public decimal cp_bh { get; set; }
        public decimal cp_vc_nt { get; set; }
        public decimal cp_vc { get; set; }
        public decimal cp_khac_nt { get; set; }
        public decimal cp_khac { get; set; }
        public decimal cp_nt { get; set; }
        public decimal cp { get; set; }
        public string ma_thue { get; set; }
        public decimal thue_suat { get; set; }
        public decimal thue { get; set; }
        public decimal thue_nt { get; set; }
        public decimal ck { get; set; }
        public decimal ck_nt { get; set; }
        public string tk_vt { get; set; }
        public string tk_gv { get; set; }
        public string tk_dt { get; set; }
        public string tk_ck { get; set; }
        public string tk_thue { get; set; }
        public short ln { get; set; }
        public string ma_vv { get; set; }
        public string ma_td { get; set; }
        public string ma_td2 { get; set; }
        public string ma_td3 { get; set; }
        public decimal sl_td1 { get; set; }
        public decimal sl_td2 { get; set; }
        public decimal sl_td3 { get; set; }
        public string gc_td1 { get; set; }
        public string gc_td2 { get; set; }
        public string gc_td3 { get; set; }
        public System.DateTime ngay_td1 { get; set; }
        public System.DateTime ngay_td2 { get; set; }
        public System.DateTime ngay_td3 { get; set; }
        public string stt_rec_sq1 { get; set; }
        public short ln_sq1 { get; set; }
        public string so_ct_sq1 { get; set; }
        public decimal so_luong_con_lai { get; set; }
        public decimal so_luong0_con_lai { get; set; }
        public string so_dh { get; set; }
        public string so_seri_vt { get; set; }
        public short app_yn_i { get; set; }
        public decimal sl_duyet { get; set; }
        public string ma_ck { get; set; }
        public decimal pt_ck { get; set; }
        public short loai_vt_xuat { get; set; }
        public decimal ton13 { get; set; }
        public short ln_dh { get; set; }
        public decimal ck2 { get; set; }
        public decimal ck_nt2 { get; set; }
        public decimal pt_ck_t { get; set; }
        public decimal pt_ck_g { get; set; }
        public decimal gia_ban { get; set; }
        public decimal gia_ban_nt { get; set; }
        public decimal tien_ban { get; set; }
        public decimal tien_ban_nt { get; set; }
        public decimal pt_ck_g2 { get; set; }
        public short h_km { get; set; }
        public decimal so_thung { get; set; }
        public decimal pt_ck_g3 { get; set; }
        public string ghi_chu { get; set; }
        public string ma_sp_me { get; set; }
        public string ma_ct_km { get; set; }
        public decimal volume { get; set; }
        public decimal weight { get; set; }
        public decimal gia0 { get; set; }
        public decimal gia_nt0 { get; set; }
        public decimal gia_web0 { get; set; }
        public decimal gia_web2 { get; set; }
        public decimal tien_web2 { get; set; }
        public decimal gia_truoc_tl2 { get; set; }
        public decimal tien_truoc_tl2 { get; set; } 
        public decimal gia_web0_tvat { get; set; }
        public decimal gia_web2_tvat { get; set; }
	}
}
