namespace ServiceAPI.Entities
{
	
	public class ph64
    {
        public decimal tien_tich_luy { get; set; }
        public int tk_online { get; set; }
        public int dh_web_yn { get; set; }
        public string ma_dvcs { get; set; }
        public string stt_rec { get; set; }
        public string ma_ct { get; set; }
        public short ma_gd { get; set; }
        public System.DateTime ngay_ct { get; set; }
        public System.DateTime ngay_lct { get; set; }
        public System.DateTime ngay_de_nghi_gh { get; set; }
        public System.DateTime ngay_hua_gh { get; set; }
        public System.DateTime ngay_ch { get; set; }
        public string thoi_gian_ch { get; set; }
        public string so_seri { get; set; }
        public string so_ct { get; set; }
        public string ma_kh { get; set; }
        public string ten_kh { get; set; }
        public string ma_kh2 { get; set; }
        public string ten_kh2 { get; set; }
        public string ong_ba { get; set; }
        public string ong_ba2 { get; set; }
        public string ong_ba3 { get; set; }
        public string dia_chi { get; set; }
        public string dia_chi2 { get; set; }
        public string dia_chi3 { get; set; }
        public string ma_so_thue { get; set; }
        public string ma_so_thue2 { get; set; }
        public string dien_giai { get; set; }
        public string ma_bp { get; set; }
        public string ma_nvbh { get; set; }
        public string ma_nx { get; set; }
        public string ma_tt { get; set; }
        public System.DateTime ngay_tt { get; set; }
        public string ma_nt { get; set; }
        public decimal ty_gia { get; set; }
        public decimal pt_tt_ck { get; set; }
        public System.DateTime ngay_tt_ck { get; set; }
        public string ma_httt { get; set; }
        public string ma_htvc { get; set; }
        public string ma_kho { get; set; }
        public decimal t_so_luong { get; set; }
        public decimal t_tien_nt { get; set; }
        public decimal t_tien { get; set; }
        public decimal t_thue_nt { get; set; }
        public decimal t_thue { get; set; }
        public short sua_thue { get; set; }
        public string ma_thue { get; set; }
        public decimal thue_suat { get; set; }
        public string tk_thue_co { get; set; }
        public string tk_thue_no { get; set; }
        public short sua_tkthue { get; set; }
        public decimal t_tien_nt2 { get; set; }
        public decimal t_tien2 { get; set; }
        public short tinh_ck { get; set; }
        public string tk_ck { get; set; }
        public decimal t_ck_nt { get; set; }
        public decimal t_ck { get; set; }
        public decimal t_tt_nt { get; set; }
        public decimal t_tt { get; set; }
        public decimal t_cp_nt { get; set; }
        public decimal t_cp { get; set; }
        public System.DateTime date0 { get; set; }
        public System.TimeSpan time0 { get; set; }
        public short user_id0 { get; set; }
        public string status { get; set; }
        public System.DateTime date2 { get; set; }
        public System.TimeSpan time2 { get; set; }
        public short user_id2 { get; set; }
        public string ma_ud1 { get; set; }
        public string ma_ud2 { get; set; }
        public string ma_ud3 { get; set; }
        public System.DateTime ngay_ud1 { get; set; }
        public System.DateTime ngay_ud2 { get; set; }
        public System.DateTime ngay_ud3 { get; set; }
        public decimal sl_ud1 { get; set; }
        public decimal sl_ud2 { get; set; }
        public decimal sl_ud3 { get; set; }
        public string gc_ud1 { get; set; }
        public string gc_ud2 { get; set; }
        public string gc_ud3 { get; set; }
        public string ten_vtthue { get; set; }
        public string ma_tinh { get; set; }
        public string ma_huyen { get; set; }
        public string dien_thoai { get; set; }
        public string dien_thoai2 { get; set; }
        public System.DateTime ngay_gh { get; set; }
        public System.TimeSpan gio_gh { get; set; }
        public short noi_gh { get; set; }
        public string ma_loai_vc { get; set; }
        public decimal so_km { get; set; }
        public decimal so_chuyen { get; set; }
        public string so_dh { get; set; }
        public short app_yn { get; set; }
        public string so_ct_sq1 { get; set; }
        public string ma_nvgh { get; set; }
        public string stt_rec_sq1 { get; set; }
        public string ma_nv_duyet { get; set; }
        public short cach_tinh_thue { get; set; }
        public decimal t_so_luong_km { get; set; }
        public decimal pt_ck_hd { get; set; }
        public decimal ck_hd_nt { get; set; }
        public decimal ck_hd { get; set; }
        public decimal pt_ck_t { get; set; }
        public decimal pt_ck_g { get; set; }
        public decimal pt_ck_g2 { get; set; }
        public short sx_yn { get; set; }
        public decimal t_sl_td1 { get; set; }
        public decimal t_sl_td2 { get; set; }
        public string stt_rec_dh { get; set; }
        public decimal pt_ck_g3 { get; set; }
        public string ma_cn { get; set; }
        public string so_po { get; set; }
        public System.DateTime ngay_po { get; set; }
        public short xacnhan_gh { get; set; }
        public System.DateTime ngayxacnhan_gh { get; set; }
        public string ghi_chu { get; set; }
        public int loai_gia { get; set; }
        public string so_ct_web { get; set; }
        public decimal gt_voucher { get; set; }
        public decimal tk_tichluy { get; set; }
        public decimal phi_vc { get; set; }
	}
}
